# Generated by Django 4.0.5 on 2022-10-17 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Areas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='address',
        ),
        migrations.AlterModelTable(
            name='area',
            table='areas',
        ),
    ]
