# Generated by Django 4.0.5 on 2022-10-18 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='类别')),
                ('parent', models.IntegerField(max_length=5, verbose_name='父类别')),
            ],
            options={
                'verbose_name': '书籍类别',
                'verbose_name_plural': '书籍类别',
                'db_table': 'book_category',
            },
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='书名')),
                ('author', models.CharField(max_length=50, verbose_name='作者')),
                ('profile', models.CharField(max_length=200, verbose_name='简介')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('image1', models.ImageField(upload_to='', verbose_name='图片1')),
                ('image2', models.ImageField(upload_to='', verbose_name='图片2')),
                ('image3', models.ImageField(upload_to='', verbose_name='图片3')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Books.bookscategory', verbose_name='从属类别')),
            ],
            options={
                'verbose_name': '书籍信息',
                'verbose_name_plural': '书籍信息',
                'db_table': 'books',
            },
        ),
    ]
