# Generated by Django 4.0.5 on 2022-10-18 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_alter_bookscategory_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookscategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='Books.bookscategory', verbose_name='父类别'),
        ),
    ]
