# Generated by Django 4.0.5 on 2022-10-22 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_sku_sales_sku_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamousBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Books.sku', verbose_name='名著')),
            ],
            options={
                'verbose_name': '名著',
                'verbose_name_plural': '名著',
                'db_table': 'famousbooks',
            },
        ),
    ]
